In [1]:
import pandas as pd
import re

In [2]:
df_1 = pd.read_pickle('batch_1_jds')
df_1.head()

,title,company,location,uid,tags,description,bullets,headers
0,PhD Program & Lab Manager (Hybrid) job,Mass General Brigham,"Charlestown, MA",48022361,"[PhD, Masters Degree, Bachelor's Degree, Entry...",DescriptionJob Summary:The School of Health an...,"[Maintains appropriate office systems, word pr...","[Job Summary:, Job Duties:, Program Manager Ro..."
1,PhD Program & Lab Manager (Hybrid) job,Massachusetts General Hospital,"Charlestown, MA",47983977,"[PhD, Masters Degree, Bachelor's Degree, Entry...",DescriptionJob Summary:The School of Health an...,"[Maintains appropriate office systems, word pr...","[Job Summary:, Job Duties:, Program Manager Ro..."
2,Assistant Professor - Clinical PhD Program - L...,Bertelsmann,"Los Angeles, CA",48973936,"[PhD, Fortune500, Media, Junior, Full-Time]",Assistant Professor - Clinical PhD Program - L...,[Active scholarship and/or relevant teaching e...,"[Our Mission:, Our Vision:, Duties & Responsib..."
3,Data Scientist / Statistician Intern (BS / MS ...,Lubrizol,"Hazelwood, DE",39232138,"[PhD, Bachelor's Degree, Data Science, Program...","Lubrizol, a Berkshire Hathaway company, is a m...",[Create predictive models by mining complex da...,[Data Scientist / Statistician Intern (BS/MS/P...
4,PhD Scientist Internship job,Danaher Corporation,"Madison, WI",49810371,"[PhD, Fortune500, Publicly Listed, Conglomerat...",Aldevron is an industry pioneer with a core co...,[Express recombinant proteins in microbial or ...,"[Job Summary:, Responsibilities:, Qualificatio..."

In [3]:
df_2 = pd.read_pickle('batch_2_jds')
df_2.head()

,title,company,location,uid,tags,description,bullets,headers
0,Staff Research Scientist - Identity and Authen...,Visa,"Atlanta, GA",48994948,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Conduct fundamental and applied research on d...,"[Join Visa: A Network Working for Everyone., R..."
1,PostDoctoral Scholar - Robotic / Force Control...,University of California Berkeley,"June, MO",48792544,"[PhD, Mechanical Engineering, Postdoc, Univers...",Position overviewSalary range: The annual sala...,[Tactile sensor design and integration with TM...,"[Salary range:, Percent time:, Anticipated sta..."
2,"Assistant Professor, Information Design and Da...",Northeastern University,"Boston, MA",47943028,"[PhD, MFA, Bachelor's Degree, Universities, Da...","About Northeastern:Founded in 1898, Northeaste...",[],"[About Northeastern:, About the Opportunity:, ..."
3,Research Scholar - Cancer Research Program job,Eastern Virginia Medical School,"Norfolk, VA",47615956,"[PhD, Universities, Junior, Full-Time, MD]","OverviewCancer Biology Laboratory (PI, Dr. Amy...",[],"[Overview, Responsibilities, Qualifications, L..."
4,Research Fellow / Day / 40 HRS / BWH Neurology...,Brigham and Women's Hospital,"Boston, MA",47550874,"[PhD, Biology, Hospitals, Postdoc, Full-Time]",DescriptionSynaptic and Network Development (S...,[PhD degree (or about to be awarded at PhD) in...,"[Expertise required, PhD degree (or about to b..."

In [4]:
df_3 = pd.read_pickle('batch_3_jds')
df_3.head()

,title,company,location,uid,tags,description,bullets,headers
0,Post Doctoral Fellow - Division of Digestive D...,Emory University,"Atlanta, GA",46138113,"[PhD, Universities, Junior, Full-Time, MD]",Discover Your Career at Emory UniversityEmory ...,[],"[Discover Your Career at Emory University, Des..."
1,Assistant Research Scientist job,Texas A&M University,"College Station, TX",46026714,"[PhD, Universities, Junior, Programming, Data ...",Job TitleAssistant Research ScientistAgencyTex...,"[Appropriate PhD, Relevant professional experi...","[Job Title, Agency, Department, Proposed Minim..."
2,Program Administrator (Academic Services Profe...,University of Colorado,"Aurora, CO",45989129,"[PhD, Bachelor's Degree, Universities, Event M...",University StaffDescriptionUniversity of Color...,[Applications are accepted electronically ONLY...,[University of Colorado | CU Anschutz Medical ...
3,Cross Domain Solutions (CDS) System Engineer job,Peraton,"Annapolis Junction, MD",45950924,"[Senior, PhD, Bachelor's Degree, IT Services, ...",Peraton drives missions of consequence spannin...,"[Bachelors Degree in System Engineering, Compu...","[Basic Qualifications:, Preferred Qualificatio..."
4,Server Performance Architect - 136824 job,AMD,"Austin, TX",45935025,"[PhD, Bachelor's Degree, Fortune500, Publicly ...","What you do at AMD changes everything At AMD, ...","[Impact microarchitecture exploration, perform...","[What you do at AMD changes everything, The Ro..."

In [5]:
df_4 = pd.read_pickle('batch_4_jds')
df_4.head()

,title,company,location,uid,tags,description,bullets,headers
0,Research Lab Manager 1 - Mendillo Lab (New) job,Northwestern University,"Chicago, IL",48594634,"[PhD, Masters Degree, Bachelor's Degree, Unive...",Department: MED-Biochem&Molecular GeneticsSala...,[Manages technical operations of a lab involve...,"[Department:, Salary/Grade:, Job Summary:, Spe..."
1,Assistant Professor (Posting) job,Northwestern University,"Evanston, IL",48594600,"[PhD, MFA, Masters Degree, Universities, Full-...",Assistant ProfessorPerformance Studies & Afric...,"[Advanced degree (MFA, PhD, DMA, etc.) or equi...","[Assistant Professor, Performance Studies & Af..."
2,"Senior Product Manager, Visa Direct Cross Bord...",Visa,"Miami, FL",48584235,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[End to end deployment of key enablers to supp...,"[Join Visa A Network Working for Everyone., Re..."
3,"Senior Risk Manager, Regulatory & Risk Governa...",Visa,"Atlanta, GA",48583939,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[U.S. supervisory exams and reviews of Visa by...,"[Join Visa: A Network Working for Everyone., E..."
4,Deloitte Risk & Financial Advisory Solution De...,Deloitte,"Denver, CO",38982822,"[Consulting Firms, Auditors, Fortune500, Partn...",Position SummaryAre you interested in improvin...,[Learn to manage and operate one or more indus...,[Work you’ll do]

In [6]:
df_5 = pd.read_pickle('batch_5_jds')
df_5.head()

,title,company,location,uid,tags,description,bullets,headers
0,Applied Scientist job,Amazon,"Seattle, WA",24130921,"[PhD, Masters Degree, Fortune500, Conglomerate...",DESCRIPTIONDo you want to join an innovative t...,"[, Use statistical and machine learning techni...",[]
1,"Software Engineering Intern, DL Inference Depl...",NVIDIA,"Santa Clara, CA",23554431,"[PhD, Masters Degree, Bachelor's Degree, Entry...",NVIDIA has continuously reinvented itself over...,[Develop production grade GPU-accelerated ML i...,"[What you’ll be doing:, What we need to see:, ..."
2,PostDoctoral Research Scientist job,Columbia University,"New York City, NY",24371884,"[PhD, Universities, Postdoc, Full-Time]",Summary DescriptionThe Division of Molecular G...,[],[]
3,Faculty. Instructor. Research job,The University of Pittsburgh,"Pittsburgh, PA",21061346,"[PhD, Universities, Junior, Programming, Lectu...",Med-Neurological Surgery-Pennsylvania-Pittsbur...,[],"[Research Instructor, Lead Neurophysiologist f..."
4,PostDoctoral Researcher - Computational Flow M...,NREL,"Golden, CO",19834346,"[PhD, Government, Energy, CleanTech, Research ...",Posting Title\nPostdoctoral Researcher – Compu...,[Perform simulations with little to no oversig...,"[Posting Title, Location, Position Type, Hours..."

In [7]:
df_6 = pd.read_pickle('batch_6_jds')
df_6.head()

,title,company,location,uid,tags,description,bullets,headers
0,Medical Writer job,Syneos Health,"New York City, NY",47098421,"[Senior, PhD, Pharma / Biotech, Healthcare, Wr...",OverviewCan you reach people with just a few w...,[Acts as agency expert on assigned products an...,"[Overview, Can you reach people with just a fe..."
1,Downstream Laboratory Associate Scientist II job,AstraZeneca,"Frederick, MD",47079815,"[PhD, Bachelor's Degree, Pharma / Biotech, For...","At AstraZeneca, we work together across global...",[This is posted as an Associate Scientist II /...,"[What you’ll do:, Education:, Why AstraZeneca?..."
2,Signal Processing Engineer job,General Atomics,"Boulder, CO",46996084,"[Senior, PhD, Masters Degree, Bachelor's Degre...","General Atomics (GA), and its affiliated compa...","[Function in an advisory or leadership role, p...","[DUTIES AND QUALIFICATIONS:, Job Qualifications:]"
3,PostDoctoral Scholar Research Associate job,University of Southern California,"Los Angeles, CA",46966064,"[PhD, Education, Universities, Postdoc, Academ...",Postdoctoral Scholar – Research Associate Keck...,[Performing genomic and epigenomic experiments...,"[Postdoctoral Scholar – Research Associate, Ke..."
4,TTU Post Doctoral Research Associate job,Texas Tech University,"Lubbock, TX",46926714,"[PhD, Universities, Junior, Full-Time, Academi...",Extended Job TitleTTU Post Doctoral Research A...,"[Cover Letter, Resume/CV, Summary of research ...",[Please provide the following with your online...

In [8]:
df_7 = pd.read_pickle('batch_7_jds')
df_7.head()

,title,company,location,uid,tags,description,bullets,headers
0,PostDoctoral Research Fellow - Metabolic Disea...,Merck & Co.,"South San Francisco, CA",49581145,"[PhD, Pharma / Biotech, Fortune500, Publicly L...",Job DescriptionNew hires in office-based roles...,[The successful candidate should have a clear ...,"[Job Description, Be a part of the legacy: Pos..."
1,"Manager, Pharmacokinetics, Dynamics and Metabo...",Sanofi,"Cambridge, MA",49566104,"[PhD, Pharma / Biotech, Healthcare, Junior, Pu...","The Pharmacokinetics, Dynamics, and Metabolism...",[Provide input to project strategy under super...,"[Job Summary:, Job Details:, Minimum requireme..."
2,"Senior Development Consultant, Visa Rules Mana...",Visa,"Ashburn, VA",49213631,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Responsible for ensuring Visa Direct Rules re...,"[Join Visa: A Network Working for Everyone., E..."
3,Senior Employee Relations Manager job,Visa,"Austin, TX",49558503,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Partner with managers/employees to facilitate...,"[Join Visa: A Network Working for Everyone., E..."
4,"Director, Employee Resource Groups job",Visa,"Foster City, CA",49558496,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Increase and advance diverse talent through a...,"[Join Visa: A Network Working for Everyone., W..."

In [9]:
df_8 = pd.read_pickle('batch_8_jds')
df_8.head()

,title,company,location,uid,tags,description,bullets,headers
0,"Director, Visa Business Solutions, Risk Busine...",Visa,"Foster City, CA",48227471,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Developing partnerships with First Line of De...,"[Join Visa: A Network Working for Everyone., T..."
1,Senior Cybersecurity Analyst job,Visa,"Foster City, CA",48227342,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Must be able to work with Global teams with f...,"[Join Visa: A Network Working for Everyone., W..."
2,HPLC / MS Method Development Senior Scientist job,Eurofins,"Lake Forest, IL",48207528,"[Senior, PhD, Bachelor's Degree, Pharma / Biot...",Company DescriptionEurofins Scientific is an i...,[Support the development & validation of LC-MS...,"[Responsibilities will include, but are not li..."
3,"Solution Management, Manager job",Visa,"Foster City, CA",48136365,"[MBA, PhD, Masters Degree, Bachelor's Degree, ...",Company DescriptionVisa is a world leader in d...,[Lead Visa Digital Product commercial rollouts...,"[Join Visa: A Network Working for Everyone., E..."
4,Faculty Professor job,The University of Pittsburgh,"Pittsburgh, PA",48133877,"[PhD, Universities, Full-Time, MD, Bioinformat...",Med-Medicine-Pennsylvania-Pittsburgh-(Co-Direc...,[],[]

In [10]:
df_9 = pd.read_pickle('batch_9_jds')
df_9.head()

,title,company,location,uid,tags,description,bullets,headers
0,"Assistant Professor, Associate Professor or Pr...",Oregon Health & Science University,"Beaverton, OR",45519755,"[PhD, Universities, Hospitals, Healthcare, Jun...",Department OverviewResearch in the field of ma...,[],"[Department Overview, Function/Duties of Posit..."
1,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45519722,"[PhD, Universities, Hospitals, Healthcare, Pos...",Function/Duties of PositionThis is a junior le...,"[PhD in related field, Successful candidates a...","[Function/Duties of Position, Required Qualifi..."
2,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45519279,"[PhD, Universities, Hospitals, Healthcare, Jun...",Function/Duties of PositionWe are seeking a re...,"[Manipulating and producing plasmid DNAs, whic...","[Function/Duties of Position, Required Qualifi..."
3,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45518604,"[PhD, Universities, Hospitals, Healthcare, Mid...",Department OverviewThe OHSU Knight Cancer Inst...,[We act BOLDLY—Breakthroughs require pushing t...,"[Department Overview, Function/Duties of Posit..."
4,"Associate Director of Diversity, Equity, and I...",Oregon Health & Science University,"Portland, OR",45518074,"[PhD, Universities, Hospitals, Healthcare, Mid...",Department OverviewThe Knight Cancer Institute...,[As a leader in addressing healthcare disparit...,"[0.2 FTE, 1.0 FTE, Position Summary:, Goals an..."

In [11]:
df_10 = pd.read_pickle('batch_10_jds')
df_10.head()

,title,company,location,uid,tags,description,bullets,headers
0,"Assistant Professor, Associate Professor or Pr...",Oregon Health & Science University,"Beaverton, OR",45519755,"[PhD, Universities, Hospitals, Healthcare, Jun...",Department OverviewResearch in the field of ma...,[],"[Department Overview, Function/Duties of Posit..."
1,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45519722,"[PhD, Universities, Hospitals, Healthcare, Pos...",Function/Duties of PositionThis is a junior le...,"[PhD in related field, Successful candidates a...","[Function/Duties of Position, Required Qualifi..."
2,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45519279,"[PhD, Universities, Hospitals, Healthcare, Jun...",Function/Duties of PositionWe are seeking a re...,"[Manipulating and producing plasmid DNAs, whic...","[Function/Duties of Position, Required Qualifi..."
3,PostDoctoral Scholar job,Oregon Health & Science University,"Portland, OR",45518604,"[PhD, Universities, Hospitals, Healthcare, Mid...",Department OverviewThe OHSU Knight Cancer Inst...,[We act BOLDLY—Breakthroughs require pushing t...,"[Department Overview, Function/Duties of Posit..."
4,"Associate Director of Diversity, Equity, and I...",Oregon Health & Science University,"Portland, OR",45518074,"[PhD, Universities, Hospitals, Healthcare, Mid...",Department OverviewThe Knight Cancer Institute...,[As a leader in addressing healthcare disparit...,"[0.2 FTE, 1.0 FTE, Position Summary:, Goals an..."

In [12]:
## Concatenate data
df_all = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10], axis=0, ignore_index=True)
df_all.head()

,title,company,location,uid,tags,description,bullets,headers
0,PhD Program & Lab Manager (Hybrid) job,Mass General Brigham,"Charlestown, MA",48022361,"[PhD, Masters Degree, Bachelor's Degree, Entry...",DescriptionJob Summary:The School of Health an...,"[Maintains appropriate office systems, word pr...","[Job Summary:, Job Duties:, Program Manager Ro..."
1,PhD Program & Lab Manager (Hybrid) job,Massachusetts General Hospital,"Charlestown, MA",47983977,"[PhD, Masters Degree, Bachelor's Degree, Entry...",DescriptionJob Summary:The School of Health an...,"[Maintains appropriate office systems, word pr...","[Job Summary:, Job Duties:, Program Manager Ro..."
2,Assistant Professor - Clinical PhD Program - L...,Bertelsmann,"Los Angeles, CA",48973936,"[PhD, Fortune500, Media, Junior, Full-Time]",Assistant Professor - Clinical PhD Program - L...,[Active scholarship and/or relevant teaching e...,"[Our Mission:, Our Vision:, Duties & Responsib..."
3,Data Scientist / Statistician Intern (BS / MS ...,Lubrizol,"Hazelwood, DE",39232138,"[PhD, Bachelor's Degree, Data Science, Program...","Lubrizol, a Berkshire Hathaway company, is a m...",[Create predictive models by mining complex da...,[Data Scientist / Statistician Intern (BS/MS/P...
4,PhD Scientist Internship job,Danaher Corporation,"Madison, WI",49810371,"[PhD, Fortune500, Publicly Listed, Conglomerat...",Aldevron is an industry pioneer with a core co...,[Express recombinant proteins in microbial or ...,"[Job Summary:, Responsibilities:, Qualificatio..."

In [14]:
df_all.tail()

,title,company,location,uid,tags,description,bullets,headers
6870,Senior Biostatistician job,Blueprint Medicines,"Cambridge, MA",49822029,"[PhD, Pharma / Biotech, Healthcare, Publicly L...","Senior Biostatistician Cambridge, MARequisitio...","[Contribute to clinical protocol development, ...","[Senior Biostatistician, What will you do?, Wh..."
6871,Program Master Scheduler / Risk Manager job,Rolls-Royce,"Indianapolis, IN",49821707,"[PhD, Bachelor's Degree, Automotive, Risk Mana...","Job DescriptionProgram LeadIndianapolis, INWe ...",[Contribute as a key team member in new opport...,"[Job Description, Program Lead, Indianapolis, ..."
6872,"Regional Director, Medical Science Liaisons - ...",Blueprint Medicines,"Cambridge, MA",49821023,"[PhD, Pharma / Biotech, Healthcare, Biology, M...","Regional Director, Medical Science Liaisons (R...","[Build, manage, and DEVELOP a high performing,...","[Regional Director, Medical Science Liaisons (..."
6873,"Medical Science Liaison, Southeast (Rare Disea...",Blueprint Medicines,"Nashville, TN",49821017,"[PhD, Pharma / Biotech, Healthcare, Biology, J...","Medical Science Liaison, Southeast (Rare Disea...",[Identify key opinion leaders and cultivate a ...,"[Medical Science Liaison, Southeast (Rare Dise..."
6874,IFS Standard Cell Library Lead job,Intel,"Hillsboro, OR",49820736,"[PhD, Bachelor's Degree, Fortune500, Publicly ...",Job ID: JR0217686Job Category: EngineeringPrim...,[Engage with the technologists from both custo...,"[Job Description, Qualifications, Inside this ..."

In [13]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6875 entries, 0 to 6874
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        6875 non-null   object
 1   company      6875 non-null   object
 2   location     6875 non-null   object
 3   uid          6875 non-null   object
 4   tags         6875 non-null   object
 5   description  6875 non-null   object
 6   bullets      6875 non-null   object
 7   headers      6875 non-null   object
dtypes: object(8)
memory usage: 429.8+ KB

In [15]:
df_all.to_csv('tapwage_corpus_may_2022.csv', index=False)

In [16]:
## Pickle this dataframe!
df_all.to_pickle('all_tapwage_jds')